// StarkFit contract ABI - generated from Cairo compilation
export const STARKFIT_ABI = [
  {
    type: "impl",
    name: "StarkFitImpl",
    interface_name: "starkfit_contracts::starkfit::IStarkFit",
  },
  {
    type: "struct",
    name: "core::integer::u256",
    members: [
      { name: "low", type: "core::integer::u128" },
      { name: "high", type: "core::integer::u128" },
    ],
  },
  {
    type: "struct",
    name: "starkfit_contracts::starkfit::Challenge",
    members: [
      { name: "id", type: "core::integer::u64" },
      { name: "creator", type: "core::starknet::contract_address::ContractAddress" },
      { name: "token", type: "core::starknet::contract_address::ContractAddress" },
      { name: "stake_amount", type: "core::integer::u256" },
      { name: "duration_days", type: "core::integer::u32" },
      { name: "step_goal", type: "core::integer::u32" },
      { name: "start_time", type: "core::integer::u64" },
      { name: "active_players", type: "core::integer::u32" },
      { name: "total_players", type: "core::integer::u32" },
      { name: "total_pool", type: "core::integer::u256" },
      { name: "is_active", type: "core::bool" },
      { name: "is_ended", type: "core::bool" },
    ],
  },
  {
    type: "struct",
    name: "starkfit_contracts::starkfit::PlayerStatus",
    members: [
      { name: "is_joined", type: "core::bool" },
      { name: "is_active", type: "core::bool" },
      { name: "has_claimed", type: "core::bool" },
      { name: "last_verified_day", type: "core::integer::u32" },
    ],
  },
  {
    type: "struct",
    name: "starkfit_contracts::starkfit::PredictionMarket",
    members: [
      { name: "id", type: "core::integer::u64" },
      { name: "challenge_id", type: "core::integer::u64" },
      { name: "player", type: "core::starknet::contract_address::ContractAddress" },
      { name: "token", type: "core::starknet::contract_address::ContractAddress" },
      { name: "yes_pool", type: "core::integer::u256" },
      { name: "no_pool", type: "core::integer::u256" },
      { name: "is_resolved", type: "core::bool" },
      { name: "outcome", type: "core::bool" },
    ],
  },
  {
    type: "interface",
    name: "starkfit_contracts::starkfit::IStarkFit",
    items: [
      {
        type: "function",
        name: "create_challenge",
        inputs: [
          { name: "token", type: "core::starknet::contract_address::ContractAddress" },
          { name: "stake_amount", type: "core::integer::u256" },
          { name: "duration_days", type: "core::integer::u32" },
          { name: "step_goal", type: "core::integer::u32" },
        ],
        outputs: [{ type: "core::integer::u64" }],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "join_challenge",
        inputs: [{ name: "challenge_id", type: "core::integer::u64" }],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "submit_steps",
        inputs: [
          { name: "challenge_id", type: "core::integer::u64" },
          { name: "player", type: "core::starknet::contract_address::ContractAddress" },
          { name: "steps", type: "core::integer::u32" },
          { name: "day", type: "core::integer::u32" },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "eliminate_player",
        inputs: [
          { name: "challenge_id", type: "core::integer::u64" },
          { name: "player", type: "core::starknet::contract_address::ContractAddress" },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "end_challenge",
        inputs: [{ name: "challenge_id", type: "core::integer::u64" }],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "claim_reward",
        inputs: [{ name: "challenge_id", type: "core::integer::u64" }],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "create_market",
        inputs: [
          { name: "challenge_id", type: "core::integer::u64" },
          { name: "player", type: "core::starknet::contract_address::ContractAddress" },
        ],
        outputs: [{ type: "core::integer::u64" }],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "bet_yes",
        inputs: [
          { name: "market_id", type: "core::integer::u64" },
          { name: "amount", type: "core::integer::u256" },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "bet_no",
        inputs: [
          { name: "market_id", type: "core::integer::u64" },
          { name: "amount", type: "core::integer::u256" },
        ],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "resolve_market",
        inputs: [{ name: "market_id", type: "core::integer::u64" }],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "claim_winnings",
        inputs: [{ name: "market_id", type: "core::integer::u64" }],
        outputs: [],
        state_mutability: "external",
      },
      {
        type: "function",
        name: "get_challenge",
        inputs: [{ name: "challenge_id", type: "core::integer::u64" }],
        outputs: [{ type: "starkfit_contracts::starkfit::Challenge" }],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "get_player_status",
        inputs: [
          { name: "challenge_id", type: "core::integer::u64" },
          { name: "player", type: "core::starknet::contract_address::ContractAddress" },
        ],
        outputs: [{ type: "starkfit_contracts::starkfit::PlayerStatus" }],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "get_market",
        inputs: [{ name: "market_id", type: "core::integer::u64" }],
        outputs: [{ type: "starkfit_contracts::starkfit::PredictionMarket" }],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "get_challenge_count",
        inputs: [],
        outputs: [{ type: "core::integer::u64" }],
        state_mutability: "view",
      },
      {
        type: "function",
        name: "get_market_count",
        inputs: [],
        outputs: [{ type: "core::integer::u64" }],
        state_mutability: "view",
      },
    ],
  },
  {
    type: "constructor",
    name: "constructor",
    inputs: [
      { name: "owner", type: "core::starknet::contract_address::ContractAddress" },
      { name: "oracle", type: "core::starknet::contract_address::ContractAddress" },
    ],
  },
  {
    type: "event",
    name: "starkfit_contracts::starkfit::StarkFit::ChallengeCreated",
    kind: "struct",
    members: [
      { name: "challenge_id", type: "core::integer::u64", kind: "key" },
      { name: "creator", type: "core::starknet::contract_address::ContractAddress", kind: "data" },
      { name: "token", type: "core::starknet::contract_address::ContractAddress", kind: "data" },
      { name: "stake_amount", type: "core::integer::u256", kind: "data" },
      { name: "duration_days", type: "core::integer::u32", kind: "data" },
      { name: "step_goal", type: "core::integer::u32", kind: "data" },
    ],
  },
  {
    type: "event",
    name: "starkfit_contracts::starkfit::StarkFit::PlayerJoined",
    kind: "struct",
    members: [
      { name: "challenge_id", type: "core::integer::u64", kind: "key" },
      { name: "player", type: "core::starknet::contract_address::ContractAddress", kind: "key" },
    ],
  },
  {
    type: "event",
    name: "starkfit_contracts::starkfit::StarkFit::PlayerEliminated",
    kind: "struct",
    members: [
      { name: "challenge_id", type: "core::integer::u64", kind: "key" },
      { name: "player", type: "core::starknet::contract_address::ContractAddress", kind: "key" },
    ],
  },
  {
    type: "event",
    name: "starkfit_contracts::starkfit::StarkFit::Event",
    kind: "enum",
    variants: [
      { name: "ChallengeCreated", type: "starkfit_contracts::starkfit::StarkFit::ChallengeCreated", kind: "nested" },
      { name: "PlayerJoined", type: "starkfit_contracts::starkfit::StarkFit::PlayerJoined", kind: "nested" },
      { name: "PlayerEliminated", type: "starkfit_contracts::starkfit::StarkFit::PlayerEliminated", kind: "nested" },
    ],
  },
] as const;
